services:
  netskope-mdm-generator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - /usr/src/app/client/node_modules
      - /usr/src/app/server/node_modules
    command: npm run start 