FROM node:18

WORKDIR /usr/src/app

# Copy package.json files
COPY package*.json ./
COPY client/package*.json ./client/
COPY server/package*.json ./server/

# Install dependencies
RUN npm install && \
    cd client && npm install && \
    cd ../server && npm install

# Copy the rest of the application code
COPY . .

# Set permissions
RUN chown -R node:node /usr/src/app

USER node

EXPOSE 3000 3001

CMD ["npm", "run", "start"] 